### ISSUE TITLE
Clustering directed labelled graphs of different sizes

### ISSUE THREAD

**Issue by FMestre1** [DianeDuroux/netANOVA#1]
Is it possible to use these functions to conduct a clustering analysis, in labelled directed graphs of different sizes. For what I understand the functions require that the adjacency matrices have the same size. Thanks.

**Comment by DianeDuroux** [comment]
Yes, it is possible. You just need to adapt the option _meth_ in the function _initialization_ to apply a metric that can handle your type of network. For instance, for labeled directed graphs of different sizes, you could choose the _random walk kernel_: init=initialization(input_networks, meth="randomWalkKernel", mode="directed"). Then you can apply the main netANOVA function as usual: output=netANOVA(Dist=init[[3]],  t=k).

**Comment by FMestre1** [comment]
Thanks!
